version: '2.1'
# ports - "host:container" i.e. published:internal
services:
  bt:
    image: linuxserver/transmission
    environment:
      TZ: "Europe/London"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - /var/transmission/config/:/config
      - /var/transmission/downloads/:/downloads
      - /var/transmission/watch/:/watch
  st:
    image: linuxserver/syncthing
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - /var/syncthing/config/:/config
      - /var/syncthing/data/:/data
  st2:
    image: linuxserver/syncthing
    ports:
      - "8385:8384"
      - "22001:22000"
      - "21028:21027/udp"
    volumes:
      - /var/syncthing2/config/:/config
      - /var/syncthing2/data/:/data
  zm:
    image: quantumobject/docker-zoneminder
    environment:
      TZ: "Europe/London"
    ports:
      - "8888:80"
