version: '2.1'
# reminders:
# ports - "host:container" where container is the port inside the container and host is the exposed port
services:
  bt:
    image: linuxserver/transmission
    environment:
      TZ: "Europe/London"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - /var/transmission/config/:/config
      - /var/transmission/downloads/:/downloads
      - /var/transmission/watch/:/watch
  st:
    image: linuxserver/syncthing
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - /var/syncthing/config/:/config
      - /var/syncthing/data/:/data
  st2:
    image: linuxserver/syncthing
    ports:
      - "8385:8384"
      - "22001:22000"
      - "21028:21027/udp"
    volumes:
      - /var/syncthing2/config/:/config
      - /var/syncthing2/data/:/data
# failed with Can't create missing temporary directory '/var/run/zm': Permission denied
#image: quantumobject/docker-zoneminder
  zm:
    image: dlandon/zoneminder
    environment:
      TZ: "Europe/London"
      PUID: "99"
      PGID: "100"
      SHMEM: "50%"
    ports:
      - "8888:80"
    volumes:
      - /var/zm/config:/config
      - /var/zm/data:/var/cache/zoneminder
